### ISSUE TITLE
Team 4100 State Tournament Programming TO-DO List

### ISSUE THREAD

**Issue by ToiletCommander** [DarlingtonProgramming/DarBots#1]
- [ ] Autonomous
    - [x] dropdown (2019/2/15)
    - [ ] sampling
        - [x] `Vuforia` + `Tensorflow` detection (2019/2/16)
        - [ ] Path schedule
        - [ ] software tolerance test
    - [ ] teammarker deposit
        - [ ] Path schedule
        - [ ] software tolerance test
    - [ ] parking
        - [ ] Path schedule
        - [ ] software tolerance test
    - [ ] overall tolerance test
- [x] Tele-Op (2019/2/16)

**Comment by ToiletCommander** [comment]
**2019/2/17 Work**   

1. In d728a0e8bb9c9d93d829a8b87af58af4cbf7e020, A `Robot4100Auto-Basic Crater` Autonomous is created and tested.
2. In d728a0e8bb9c9d93d829a8b87af58af4cbf7e020, A `Robot4100Auto-Crater` is created but the path is pending for more tests.

**Comment by ToiletCommander** [comment]
**2019/2/18 Work**
1. Crater Program almost finished.
